apiVersion: v1
kind: Service
metadata:
  name: postgres-service # Nome DNS para outros microsserviços se conectarem
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432 # Porta que o serviço expõe
      targetPort: 5432 # Porta do container PostgreSQL
  type: ClusterIP # Acessível apenas dentro do cluster